using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using MahApps.Metro.IconPacks;
using V3SClient.libs;

namespace V3SClient.UI.Views
{
    public sealed class PtzControlPanel_v3 : UserControl
    {
        private readonly string _cameraId;
        private readonly CancellationTokenSource _cancel = new CancellationTokenSource();
        private readonly Slider _pan = SliderOf(6), _tilt = SliderOf(5), _zoom = SliderOf(4);
        private readonly ComboBox _streams = new ComboBox { Width = 70, Height = 30, Margin = new Thickness(8, 0, 6, 0), MaxDropDownHeight = 140 };
        private readonly ComboBox _presets = new ComboBox { Height = 36, MinWidth = 170, Margin = new Thickness(0, 8, 8, 0) };
        private int _session; private bool _pressed; private Button _active;
        public event EventHandler CloseRequested; public event Action<string> StreamChanged; public event Action<bool> ConnectionChanged;

        public PtzControlPanel_v3(string cameraId, IEnumerable<string> streams = null)
        {
            _cameraId = cameraId ?? string.Empty; Background = Brush("#071724"); Configure(_streams); Configure(_presets);
            foreach (var s in (streams ?? new[] { "main", "sub1", "sub2" }).Where(x => !string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase)) _streams.Items.Add(s);
            if (_streams.Items.Count == 0) _streams.Items.Add("main"); _streams.SelectedIndex = 0;
            _streams.SelectionChanged += (s, e) => { if (_streams.SelectedItem != null) StreamChanged?.Invoke(_streams.SelectedItem.ToString()); };
            PreviewMouseLeftButtonUp += (s, e) => StopActive(); PreviewMouseMove += (s, e) => { if (_pressed && Mouse.LeftButton != MouseButtonState.Pressed) StopActive(); };
            Loaded += async (s, e) => await LoadPresets(); Unloaded += (s, e) => { _session++; StopActive(); _cancel.Cancel(); }; Content = Build();
        }

        private UIElement Build()
        {
            var root = new Grid { Margin = new Thickness(14, 10, 14, 14) }; for (var i = 0; i < 4; i++) root.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
            var header = new Grid { Margin = new Thickness(0, 0, 0, 22) }; header.ColumnDefinitions.Add(new ColumnDefinition()); for (var i = 0; i < 3; i++) header.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });
            var title = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center }; title.Children.Add(new PackIconMaterial { Kind = PackIconMaterialKind.Crosshairs, Width = 15, Height = 15, Foreground = Brush("#16B9FF"), Margin = new Thickness(0, 0, 7, 0) }); title.Children.Add(new TextBlock { Text = "PTZ", Foreground = Brushes.White, FontSize = 13, FontWeight = FontWeights.Bold }); title.Children.Add(new Ellipse { Width = 7, Height = 7, Fill = Brush("#20C978"), Margin = new Thickness(8, 0, 5, 0), VerticalAlignment = VerticalAlignment.Center }); title.Children.Add(new TextBlock { Text = _cameraId, Foreground = Brushes.White, FontSize = 12, TextTrimming = TextTrimming.CharacterEllipsis, ToolTip = _cameraId }); header.Children.Add(title);
            Grid.SetColumn(_streams, 1); header.Children.Add(_streams); var connected = true; var link = Header("plug", "Ngắt kết nối"); link.Click += (s, e) => { connected = !connected; link.Content = HeaderIcon(connected ? PackIconMaterialKind.PowerPlug : PackIconMaterialKind.PowerPlugOff); link.ToolTip = connected ? "Ngắt kết nối" : "Kết nối"; ConnectionChanged?.Invoke(connected); }; Grid.SetColumn(link, 2); header.Children.Add(link); var close = Header("×", "Đóng PTZ"); close.Click += (s, e) => CloseRequested?.Invoke(this, EventArgs.Empty); Grid.SetColumn(close, 3); header.Children.Add(close); Grid.SetRow(header, 0); root.Children.Add(header);
            var controls = new Grid { Margin = new Thickness(0, 0, 0, 18) }; controls.ColumnDefinitions.Add(new ColumnDefinition()); controls.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(58) }); var pad = new Grid { Width = 142, Height = 142, HorizontalAlignment = HorizontalAlignment.Center }; for (var i = 0; i < 3; i++) { pad.RowDefinitions.Add(new RowDefinition()); pad.ColumnDefinitions.Add(new ColumnDefinition()); } Direction(pad, "▲", 0, 1, 0, 1, 0); Direction(pad, "◀", 1, 0, -1, 0, 0); Direction(pad, "●", 1, 1, 0, 0, 0); Direction(pad, "▶", 1, 2, 1, 0, 0); Direction(pad, "▼", 2, 1, 0, -1, 0); controls.Children.Add(pad); var zoom = new StackPanel(); var plus = Button("⌕+", "Phóng to"); plus.Click += async (s, e) => await Move(0, 0, 1); var minus = Button("⌕−", "Thu nhỏ"); minus.Click += async (s, e) => await Move(0, 0, -1); zoom.Children.Add(plus); zoom.Children.Add(minus); Grid.SetColumn(zoom, 1); controls.Children.Add(zoom); Grid.SetRow(controls, 1); root.Children.Add(controls);
            var speeds = new StackPanel(); Speed(speeds, "Tốc độ Pan", _pan); Speed(speeds, "Tốc độ Tilt", _tilt); Speed(speeds, "Tốc độ Zoom", _zoom); Grid.SetRow(speeds, 2); root.Children.Add(speeds);
            var preset = new StackPanel { Margin = new Thickness(0, 18, 0, 0) }; var ph = new DockPanel(); ph.Children.Add(new TextBlock { Text = "Vị trí đặt trước", Foreground = Brushes.White, FontSize = 14, FontWeight = FontWeights.SemiBold }); var refresh = Button("↻", "Tải lại vị trí"); refresh.Width = 30; refresh.Height = 30; refresh.Click += async (s, e) => await LoadPresets(); DockPanel.SetDock(refresh, Dock.Right); ph.Children.Add(refresh); preset.Children.Add(ph); var row = new StackPanel { Orientation = Orientation.Horizontal }; row.Children.Add(_presets); var go = Button("Đi tới", "Đi tới vị trí"); go.Width = 58; go.Height = 36; go.Click += async (s, e) => { var p = _presets.SelectedItem as ApiManager.CameraPtzPreset; if (p != null) await ApiManager.Instance.GotoCameraPtzPresetAsync(_cameraId, p.Token, _cancel.Token); }; row.Children.Add(go); preset.Children.Add(row); Grid.SetRow(preset, 3); root.Children.Add(preset); return root;
        }
        private void Direction(Grid g, string text, int r, int c, double p, double t, double z) { var b = Button(string.Empty, "Điều khiển PTZ"); b.Width = 46; b.Height = 46; b.Margin = new Thickness(1); b.Tag = r == 1 && c == 1 ? null : Wedge(r, c); b.Content = new TextBlock { Text = text, Foreground = Brushes.White, FontSize = 17, FontWeight = FontWeights.Bold, RenderTransform = new TranslateTransform((c == 0 ? -12 : c == 2 ? 12 : 0), (r == 0 ? -12 : r == 2 ? 12 : 0)) }; b.Style = r == 1 && c == 1 ? RoundStyle("#123B66", "#2D73C7", 23) : WedgeStyle(); b.PreviewMouseLeftButtonDown += (s, e) => { if (_pressed) return; _pressed = true; _active = b; b.CaptureMouse(); _session++; _ = Hold(p, t, z, _session); e.Handled = true; }; b.PreviewMouseLeftButtonUp += (s, e) => { StopButton(b); e.Handled = true; }; Grid.SetRow(b, r); Grid.SetColumn(b, c); g.Children.Add(b); }
        private static string Wedge(int r, int c) { if (r == 0) return "M23,0 A34,34 0 0 1 46,23 L31,30 A13,13 0 0 0 15,30 L0,23 A34,34 0 0 1 23,0 Z"; if (r == 2) return "M0,23 A34,34 0 0 1 23,46 A34,34 0 0 1 46,23 L31,16 A13,13 0 0 0 15,16 Z"; if (c == 0) return "M0,23 A34,34 0 0 1 23,0 L30,15 A13,13 0 0 0 30,31 L23,46 A34,34 0 0 1 0,23 Z"; return "M23,0 A34,34 0 0 1 46,23 A34,34 0 0 1 23,46 L16,31 A13,13 0 0 0 16,15 Z"; }
        private async Task Hold(double p, double t, double z, int id) { try { while (id == _session && !_cancel.IsCancellationRequested) await Move(p, t, z); } catch (OperationCanceledException) { } }
        private void StopActive() { if (_active != null) StopButton(_active); }
        private void StopButton(Button b) { if (!_pressed || !ReferenceEquals(_active, b)) return; _pressed = false; _active = null; _session++; if (b.IsMouseCaptured) b.ReleaseMouseCapture(); _ = StopMove(); }
        private Task Move(double p, double t, double z) => ApiManager.Instance.MoveCameraPtzAsync(_cameraId, new ApiManager.CameraPtzMovement { duration = 10, pan = p, tilt = t, zoom = z, pan_speed = _pan.Value, tilt_speed = _tilt.Value, zoom_speed = _zoom.Value }, _cancel.Token);
        private Task StopMove() => ApiManager.Instance.MoveCameraPtzAsync(_cameraId, new ApiManager.CameraPtzMovement { duration = 1, pan = 0, tilt = 0, zoom = 0 }, _cancel.Token);
        private async Task LoadPresets() { try { _presets.Items.Clear(); foreach (var p in await ApiManager.Instance.GetCameraPtzPresetsAsync(_cameraId, _cancel.Token)) _presets.Items.Add(p); _presets.DisplayMemberPath = "Name"; } catch (OperationCanceledException) { } }
        private static void Speed(Panel p, string text, Slider s) { p.Children.Add(new TextBlock { Text = text, Foreground = Brushes.White, FontSize = 12, Margin = new Thickness(0, 4, 0, 0) }); p.Children.Add(s); }
        private static Slider SliderOf(double value) { return new Slider { Minimum = 1, Maximum = 10, Value = value, TickFrequency = 1, IsSnapToTickEnabled = true, Margin = new Thickness(0, 0, 0, 5) }; }
        private static Button Header(string text, string tip) { var b = StyledButton(string.Empty, tip, 34, 30, 16, "#0A2235"); b.Content = text == "×" ? (UIElement)new PackIconMaterial { Kind = PackIconMaterialKind.Close, Width = 15, Height = 15 } : HeaderIcon(PackIconMaterialKind.PowerPlug); return b; }
        private static UIElement HeaderIcon(PackIconMaterialKind kind) { return new PackIconMaterial { Kind = kind, Width = 15, Height = 15 }; }
        private static Button Button(string text, string tip) { return StyledButton(text, tip, 48, 42, 17, "#0A2641"); }
        private static Button StyledButton(string text, string tip, double width, double height, double fontSize, string background) { var b = new Button { Content = text, ToolTip = tip, Width = width, Height = height, FontSize = fontSize, FontWeight = FontWeights.SemiBold, Padding = new Thickness(0), Foreground = Brushes.White, Background = Brush(background), BorderBrush = Brush("#365B7D"), BorderThickness = new Thickness(1) }; b.Style = new Style(typeof(System.Windows.Controls.Button)) { Setters = { new Setter(Control.BackgroundProperty, Brush(background)), new Setter(Control.ForegroundProperty, Brushes.White), new Setter(Control.BorderBrushProperty, Brush("#365B7D")), new Setter(Control.BorderThicknessProperty, new Thickness(1)), new Setter(Control.PaddingProperty, new Thickness(0)) } }; return b; }
        private static Style RoundStyle(string background, string border, double radius) { var style = new Style(typeof(System.Windows.Controls.Button)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brush(background))); style.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brush(border))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(0))); var template = new ControlTemplate(typeof(System.Windows.Controls.Button)); var root = new FrameworkElementFactory(typeof(Border)); root.SetValue(Border.BackgroundProperty, Brush(background)); root.SetValue(Border.BorderBrushProperty, Brush(border)); root.SetValue(Border.BorderThicknessProperty, new Thickness(1)); root.SetValue(Border.CornerRadiusProperty, new CornerRadius(radius)); var content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetValue(ContentPresenter.HorizontalAlignmentProperty, HorizontalAlignment.Center); content.SetValue(ContentPresenter.VerticalAlignmentProperty, VerticalAlignment.Center); root.AppendChild(content); template.VisualTree = root; style.Setters.Add(new Setter(Control.TemplateProperty, template)); return style; }
        private static Style WedgeStyle() { var style = new Style(typeof(System.Windows.Controls.Button)); var normal = Brush("#0A2641"); var hover = Brush("#164B78"); var pressed = Brush("#226FAE"); var border = Brush("#245B9B"); style.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BackgroundProperty, normal)); style.Setters.Add(new Setter(Control.BorderBrushProperty, border)); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Triggers.Add(new Trigger { Property = System.Windows.Controls.Button.IsMouseOverProperty, Value = true, Setters = { new Setter(Control.BackgroundProperty, hover) } }); style.Triggers.Add(new Trigger { Property = System.Windows.Controls.Button.IsPressedProperty, Value = true, Setters = { new Setter(Control.BackgroundProperty, pressed), new Setter(Control.BorderBrushProperty, Brush("#4BA6F5")) } }); var template = new ControlTemplate(typeof(System.Windows.Controls.Button)); var grid = new FrameworkElementFactory(typeof(Grid)); var path = new FrameworkElementFactory(typeof(Path)); path.SetBinding(Path.DataProperty, new System.Windows.Data.Binding("Tag") { RelativeSource = new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent) }); path.SetBinding(Path.FillProperty, new System.Windows.Data.Binding("Background") { RelativeSource = new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent) }); path.SetBinding(Path.StrokeProperty, new System.Windows.Data.Binding("BorderBrush") { RelativeSource = new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent) }); path.SetValue(Path.StrokeThicknessProperty, 1.0); grid.AppendChild(path); var content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetValue(ContentPresenter.HorizontalAlignmentProperty, HorizontalAlignment.Center); content.SetValue(ContentPresenter.VerticalAlignmentProperty, VerticalAlignment.Center); grid.AppendChild(content); template.VisualTree = grid; style.Setters.Add(new Setter(Control.TemplateProperty, template)); return style; }
        private static Brush Brush(string hex) { return (Brush)new BrushConverter().ConvertFromString(hex); }
        private static void Configure(ComboBox b) { var background = Brush("#0A2235"); var border = Brush("#245B9B"); var hover = Brush("#123B66"); b.Foreground = Brushes.White; b.Background = background; b.BorderBrush = border; b.Padding = new Thickness(7, 0, 3, 0); b.VerticalContentAlignment = VerticalAlignment.Center; b.Resources[SystemColors.WindowBrushKey] = background; b.Resources[SystemColors.ControlBrushKey] = background; b.Resources[SystemColors.HighlightBrushKey] = hover; b.Resources[SystemColors.HighlightTextBrushKey] = Brushes.White; b.Resources[SystemColors.InactiveSelectionHighlightBrushKey] = hover; var textStyle = new Style(typeof(TextBox)); textStyle.Setters.Add(new Setter(Control.BackgroundProperty, background)); textStyle.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); textStyle.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(0))); textStyle.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(4, 0, 0, 0))); b.Resources[typeof(TextBox)] = textStyle; var itemStyle = new Style(typeof(ComboBoxItem)); itemStyle.Setters.Add(new Setter(Control.BackgroundProperty, background)); itemStyle.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); itemStyle.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(8, 5, 8, 5))); itemStyle.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Left)); itemStyle.Triggers.Add(new Trigger { Property = ComboBoxItem.IsHighlightedProperty, Value = true, Setters = { new Setter(Control.BackgroundProperty, hover), new Setter(Control.ForegroundProperty, Brushes.White) } }); b.ItemContainerStyle = itemStyle; b.Style = new Style(typeof(ComboBox)) { Setters = { new Setter(Control.BackgroundProperty, background), new Setter(Control.ForegroundProperty, Brushes.White), new Setter(Control.BorderBrushProperty, border), new Setter(Control.BorderThicknessProperty, new Thickness(1)), new Setter(Control.PaddingProperty, new Thickness(7, 0, 3, 0)), new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center) } }; b.Loaded += (s, e) => PaintComboTemplate(b, background, border); b.DropDownOpened += (s, e) => { var popup = b.Template.FindName("PART_Popup", b) as Popup; if (popup != null && popup.Child != null) PaintComboTemplate(popup.Child, background, border); }; }
        private static void PaintComboTemplate(DependencyObject root, Brush background, Brush border) { for (var i = 0; i < VisualTreeHelper.GetChildrenCount(root); i++) { var child = VisualTreeHelper.GetChild(root, i); var control = child as Control; if (control != null) { control.Background = background; control.Foreground = Brushes.White; control.BorderBrush = border; } var childBorder = child as Border; if (childBorder != null) { childBorder.Background = background; childBorder.BorderBrush = border; } PaintComboTemplate(child, background, border); } }
    }
}
